# Generated by Django 4.1.2 on 2022-11-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Surname', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
